{
    'name':'Ecommerce_POS',
    'depends':['base','product','point_of_sale','stock_account','sale'],
    'data':[
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/user.xml',
        'views/product.xml',
        'views/posconfig.xml',
        'views/order.xml',
        'views/inventory.xml',
    ]
}